name: Sync Community Agent READMEs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at 00:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout Repo A
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm install node-fetch@3

      - name: 🔄 Fetch community agent READMEs
        run: node fetch_agents.js

      - name: 💾 Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add developer-docs/example-projects/community
          git commit -m "chore: sync community agent READMEs from awesome-saas" || echo "No changes to commit"
          git push
